version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: 'Generate code from proto files'
    cmds:
      - protoc -I proto proto/sso.proto --go_out=./gen/go/sso --go_opt=paths=source_relative --go-grpc_out=./gen/go/sso --go-grpc_opt=paths=source_relative