version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: 'Generate code from proto files'
    vars:
      FILE: '{{.FILE | default "sso"}}'
    cmds:
      - protoc -I proto proto/{{.FILE}}.proto --go_out=./gen/go/{{.FILE}} --go_opt=paths=source_relative --go-grpc_out=./gen/go/{{.FILE}} --go-grpc_opt=paths=source_relative